[package]
name = "sigma"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rust-ini = "0.21"
miniz_oxide = "0.8.0"
sha1 = "0.10.1"
hex = "0.4.1"
indexmap = "2.7.0"
glob = "0.3.1"
walkdir = "2.3.2"
chrono = "0.4.39"
